export type Lang = 'zh' | 'en'

export const dict = {
  zh: {
    brand: 'Star Sorter',
    headline: '我的 GitHub Star 收藏',
    subline: '由 AI 每日自动分类整理的项目索引，中英双语简介。',
    countLine: (repos: number, cats: number) => `${repos} 个项目 · ${cats} 个分类`,
    updatedAt: '更新于',
    aiNote: '简介由 AI 生成',
    all: '全部',
    searchPlaceholder: '搜索项目、描述或标签…',
    sortStars: '按 Star 数',
    sortRecent: '按最近更新',
    noResults: '未找到匹配的项目',
    noResultsHint: '换个关键词或分类试试',
    loadError: '数据加载失败',
    loadErrorHint: '请刷新重试，或稍后再来',
    retry: '重试',
    languageLabel: '切换语言',
    switchLang: 'EN',
    footerNote: '每日北京时间 05:00 由 GitHub Actions 自动更新',
    syntheticNote: '当前为示例数据，首次自动运行后由真实 Star 替换',
  },
  en: {
    brand: 'Star Sorter',
    headline: 'My GitHub Stars',
    subline: 'A curated index of starred projects, auto-categorized daily by AI with bilingual summaries.',
    countLine: (repos: number, cats: number) => `${repos} projects · ${cats} categories`,
    updatedAt: 'Updated',
    aiNote: 'Summaries generated by AI',
    all: 'All',
    searchPlaceholder: 'Search projects, descriptions, or topics…',
    sortStars: 'Most stars',
    sortRecent: 'Recently updated',
    noResults: 'No matching projects',
    noResultsHint: 'Try a different keyword or category',
    loadError: 'Failed to load data',
    loadErrorHint: 'Refresh to try again',
    retry: 'Retry',
    languageLabel: 'Switch language',
    switchLang: '中文',
    footerNote: 'Auto-updated daily at 05:00 Beijing time via GitHub Actions',
    syntheticNote: 'Sample data — replaced by real stars after the first automated run',
  },
} as const

export function formatStars(n: number, lang: Lang): string {
  const trim = (s: string) => s.replace(/\.0$/, '')
  if (n >= 10000 && lang === 'zh') return `${trim((n / 10000).toFixed(1))}万`
  if (n >= 1000) return `${trim((n / 1000).toFixed(1))}k`
  return String(n)
}

export function formatDate(iso: string, lang: Lang, short = false): string {
  const d = new Date(iso)
  if (Number.isNaN(d.getTime())) return ''
  return new Intl.DateTimeFormat(lang === 'zh' ? 'zh-CN' : 'en-US', {
    year: short ? undefined : 'numeric',
    month: 'short',
    day: 'numeric',
  }).format(d)
}

// GitHub linguist 语言配色，未收录语言用灰
export const LANGUAGE_COLORS: Record<string, string> = {
  TypeScript: '#3178c6',
  JavaScript: '#f1e05a',
  Python: '#3572a5',
  Rust: '#dea584',
  Go: '#00add8',
  HTML: '#e34c26',
  CSS: '#563d7c',
  Vue: '#41b883',
  Shell: '#89e051',
  'C++': '#f34b7d',
  Java: '#b07219',
  Kotlin: '#a97bff',
  Swift: '#f05138',
  Zig: '#ec915c',
  C: '#555555',
  'C#': '#178600',
  Ruby: '#701516',
  PHP: '#4f5d95',
  Dart: '#00b4ab',
  Lua: '#000080',
  Elixir: '#6e4a7e',
  Haskell: '#5e5086',
  OCaml: '#ef7a08',
  Nix: '#7e7eff',
  Dockerfile: '#384d54',
  Solid: '#5c6bc0',
}

export function languageColor(lang: string | null): string {
  if (!lang) return '#9ca3af'
  return LANGUAGE_COLORS[lang] ?? '#9ca3af'
}
